export default [
  {
    id: 'blanketWrapVan',
    name: 'Blanket Wrap Van',
    ltl: true,
    maxLength: 53,
    maxWidth: 96,
    maxHeight: 96,
    maxWeight: 44000,
    odHeight: null,
    odLength: 48,
    odWidth: null,
    odWeight: null,
    odBump: 0.2,
    rate: 2.2
  },
  {
    id: 'curtainVan',
    name: 'Curtain Van',
    ltl: true,
    maxLength: 53,
    maxWidth: 96,
    maxHeight: 96,
    maxWeight: 44000,
    odHeight: null,
    odLength: 48,
    odWidth: null,
    odWeight: null,
    odBump: 0.2,
    rate: 2.7
  },
  {
    id: 'doubleDrop',
    name: 'Double Drop',
    ltl: false,
    maxLength: 50,
    maxWidth: 168,
    maxHeight: 168,
    maxWeight: 250000,
    odHeight: 150,
    odLength: null,
    odWidth: 102,
    odWeight: 48000,
    odBump: 0.6,
    rate: 3.25
  },
  {
    id: 'flatbed',
    name: 'Flatbed',
    ltl: true,
    maxLength: 58,
    maxWidth: 168,
    maxHeight: 108,
    maxWeight: 49000,
    odHeight: null,
    odLength: 54,
    odWidth: 102,
    odWeight: 48000,
    odBump: 0.5,
    rate: 2.2
  },
  {
    id: 'flatbedAirRide',
    name: 'FlatBed - Air Ride',
    ltl: true,
    maxLength: 58,
    maxWidth: 168,
    maxHeight: 108,
    maxWeight: 49000,
    odHeight: null,
    odLength: 54,
    odWidth: 102,
    odWeight: 48000,
    odBump: 0.5,
    rate: 2.11
  },
  {
    id: 'flatbedWithSides',
    name: 'Flatbed w/ Sides',
    ltl: true,
    maxLength: 58,
    maxWidth: 96,
    maxHeight: 108,
    maxWeight: 49000,
    odHeight: null,
    odLength: 54,
    odWidth: null,
    odWeight: 48000,
    odBump: 0.5,
    rate: 2.8
  },
  {
    id: 'hotShot',
    name: 'Hot Shot',
    ltl: false,
    maxLength: 40,
    maxWidth: 102,
    maxHeight: 120,
    maxWeight: 20000,
    odHeight: null,
    odLength: null,
    odWidth: null,
    odWeight: null,
    odBump: 0,
    rate: 1.68
  },
  {
    id: 'landollFlatbed',
    name: 'Landoll Flatbed',
    ltl: true,
    maxLength: 48,
    maxWidth: 96,
    maxHeight: 108,
    maxWeight: 49000,
    odHeight: null,
    odLength: null,
    odWidth: null,
    odWeight: 48000,
    odBump: 0.5,
    rate: 3
  },
  {
    id: 'lowboy',
    name: 'Lowboy',
    ltl: false,
    maxLength: 50,
    maxWidth: 168,
    maxHeight: 168,
    maxWeight: 250000,
    odHeight: 150,
    odLength: null,
    odWidth: 102,
    odWeight: 48000,
    odBump: 0.6,
    rate: 3.5
  },
  {
    id: 'powerOnly',
    name: 'Power Only (tow-away)',
    ltl: false,
    maxLength: 100,
    maxWidth: 168,
    maxHeight: 180,
    maxWeight: 250000,
    odHeight: 168,
    odLength: 48,
    odWidth: 102,
    odWeight: 48000,
    odBump: 0.6,
    rate: 2.09,
    escortHeight: 168
  },
  {
    id: 'reefer',
    name: 'Refrigerated Carrier (reefer)',
    ltl: true,
    maxLength: 53,
    maxWidth: 96,
    maxHeight: 96,
    maxWeight: 44000,
    odHeight: null,
    odLength: 48,
    odWidth: null,
    odWeight: null,
    odBump: 0.2,
    rate: 2.5
  },
  {
    id: 'removableGooseneck',
    name: 'Removable Gooseneck',
    ltl: false,
    maxLength: 42,
    maxWidth: 168,
    maxHeight: 168,
    maxWeight: 250000,
    odHeight: 150,
    odLength: null,
    odWidth: 102,
    odWeight: 48000,
    odBump: 0.6,
    rate: 3.14
  },
  {
    id: 'removableGooseneckExtendable',
    name: 'Removable Gooseneck Extendable',
    ltl: false,
    maxLength: 82,
    maxWidth: 168,
    maxHeight: 168,
    maxWeight: 250000,
    odHeight: 150,
    odLength: null,
    odWidth: 102,
    odWeight: 48000,
    odBump: 0.6,
    rate: 6.5
  },
  {
    id: 'rollTopConestoga',
    name: 'Roll Top Conestoga',
    ltl: true,
    maxLength: 53,
    maxWidth: 96,
    maxHeight: 96,
    maxWeight: 44000,
    odHeight: null,
    odLength: 48,
    odWidth: null,
    odWeight: null,
    odBump: 0,
    rate: 3.25
  },
  {
    id: 'stepDeck',
    name: 'Step Deck',
    ltl: true,
    maxLength: 53,
    maxWidth: 168,
    maxHeight: 126,
    maxWeight: 53000,
    odHeight: null,
    odLength: 48,
    odWidth: 102,
    odWeight: 48000,
    odBump: 0.6,
    rate: 2.17
  },
  {
    id: 'stepDeckWithRamps',
    name: 'Step Deck w/ Loading Ramps',
    ltl: true,
    maxLength: 53,
    maxWidth: 168,
    maxHeight: 126,
    maxWeight: 15000,
    odHeight: null,
    odLength: 48,
    odWidth: 102,
    odWeight: null,
    odBump: 0.6,
    rate: 2.22
  },
  {
    id: 'stretchTrailer',
    name: 'Stretch Trailer or Extendable Flatbed',
    ltl: false,
    maxLength: 100,
    maxWidth: 168,
    maxHeight: 108,
    maxWeight: 49000,
    odHeight: null,
    odLength: 60,
    odWidth: 102,
    odWeight: 48000,
    odBump: 0.5,
    rate: 3.25
  },
  {
    id: 'specializedTrailers',
    name: 'Unspecified Specialized Trailers',
    ltl: false,
    maxLength: 100,
    maxWidth: 168,
    maxHeight: 180,
    maxWeight: 250000,
    odHeight: 150,
    odLength: 48,
    odWidth: 102,
    odWeight: 48000,
    odBump: 0.6,
    rate: 3.5
  },
  {
    id: 'van',
    name: 'Van',
    ltl: true,
    maxLength: 53,
    maxWidth: 96,
    maxHeight: 96,
    maxWeight: 44000,
    odHeight: null,
    odLength: 48,
    odWidth: null,
    odWeight: null,
    odBump: 0.2,
    rate: 2.17
  },
  {
    id: 'vanAirRide',
    name: 'Van - Air Ride',
    ltl: true,
    maxLength: 53,
    maxWidth: 96,
    maxHeight: 96,
    maxWeight: 44000,
    odHeight: null,
    odLength: 48,
    odWidth: null,
    odWeight: null,
    odBump: 0.2,
    rate: 2.15
  },
  {
    id: 'vanWithLiftgate',
    name: 'Van w/ Liftgate',
    ltl: true,
    maxLength: 53,
    maxWidth: 96,
    maxHeight: 96,
    maxWeight: 44000,
    odHeight: null,
    odLength: 48,
    odWidth: null,
    odWeight: null,
    odBump: 0.2,
    rate: 2.55
  }
]
